version: '3'
services:

  app:
    build: app/.
    command: "gunicorn --bind 0.0.0.0:5000 runserver:app"

  www:
    restart: always
    build: nginx/.
    links:
      - app
    depends_on:
      - app
    ports:
      - "80:80"